apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: worker
rules:
- apiGroups:
  - policy
  resources:
  - podsecuritypolicies
  verbs:
  - use
  resourceNames:
  - nfd-worker
- apiGroups:
  - nfd.k8s-sigs.io
  resources:
  - nodefeatures
  verbs:
  - get
  - create
  - update
