apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: topology-updater
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: topology-updater
subjects:
- kind: ServiceAccount
  name: nfd-topology-updater
  namespace: node-feature-discovery
